### ISSUE TITLE
better management of data fetch when mounting / routing

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/conference-hall-beta#135]
Discussion from PR #123 

Find a way to manage data loading on routes and component mounting. Each time I have an URL with param eventId, I have to do a loader like that, I think I could factorize this code in a better way.

```es6
const mapStore = (store) => {
  const eventId = getRouterParam('eventId')(store.getState())
  const event = store.data.events.get(eventId)
  return {
    loaded: !!event,
    eventId,
    load: () => store.dispatch('@@ui/ON_LOAD_EVENT'),
  }
}
export default compose(
  forRoute.absolute('PROPOSALS'),
  inject(mapStore),
  loader,
)(Proposals)
```

----

*Idea from @fabienjuif :*
Look at the new hoc `listen`.
Maybe we can dispatch an event in this hoc like `@@krml/LISTEN_PLUGUED>${componentName}`
And in the listeners you plug with `listen` hoc, you catch that ?

**Comment by fabienjuif** [comment]
This LISTEN event is already present into `k-ramel`

**container**
```js
import listeners from './proposals.listeners'

export default listen(listeners, 'proposals')(Proposals)
```

**listeners**
```js
import { when, reaction } from 'k-ramel'

export default [
    when('@@krml/LISTENERS>ADDED>proposals')(reaction((action, store) => {
      console.log('yo')
    })),
]
```

**Comment by bpetetot** [comment]
Yes I know ;) this issue is here just to do it.

**Comment by bpetetot** [comment]
Done for proposals in PR #284 must be done over other app's parts in a bigger refactoring
