### ISSUE TITLE
ascenceur en double

### ISSUE THREAD

**Issue by gmembre-zenika** [bpetetot/conference-hall-beta#146]
Chrome : 60.0.3112 
![image](https://user-images.githubusercontent.com/7294764/36374025-4323fbb6-156a-11e8-957a-5ad880eaab92.png)

Il y a des ascenceurs de partout (en plein écran ou pas)
![image](https://user-images.githubusercontent.com/7294764/36374000-2c4b67f8-156a-11e8-93ef-3dbbd6afb747.png)

**Comment by bpetetot** [comment]
Merci pour le retour ;)
