### ISSUE TITLE
[speaker] submit a talk from the talk page

### ISSUE THREAD

**Issue by nlepage** [bpetetot/conference-hall-beta#157]
It'd be nice to be able to submit a talk from the talk page.

It would require to add a "Submit" button in the "Submissions" card of the talk :

![image](https://user-images.githubusercontent.com/19571875/36542321-ca940ed8-17e0-11e8-8d7d-178d7331289e.png)

Then slightly change the submission process to replace the "Talk selection" step by an "Event selection" step :

![image](https://user-images.githubusercontent.com/19571875/36542552-655dc526-17e1-11e8-981a-20952bfeede9.png)

This is just a suggestion, what do you think ?

**Comment by bpetetot** [comment]
Yes it's a good idea ! I add it as feature.
Thanks

**Comment by nlepage** [comment]
May I make a PR ? I can't assign myself to the issue...

**Comment by bpetetot** [comment]
Thanks for the help ;) Don't hesitate if you need help
