### ISSUE TITLE
No events in side bar

### ISSUE THREAD

**Issue by nlepage** [bpetetot/conference-hall-beta#158]
When arriving from the "I'm a speaker" / "I'm an organizer" choice page, after clicking on "I'm a speaker", no events appear in the sidebar :

![image](https://user-images.githubusercontent.com/19571875/36548228-062c2cf0-17f0-11e8-90f0-3de7f62ccdaf.png)

After hitting refresh, the events are correctly loaded.

**Comment by bpetetot** [comment]
Yes for now the current event is just stored in localstorage and I must forget to load it when you come from home page. I have to persist it in the database and load it at the right time

**Comment by bpetetot** [comment]
Fixed in #160
