### ISSUE TITLE
Cohérence dans les libellés

### ISSUE THREAD

**Issue by ghost** [bpetetot/conference-hall-beta#179]
Dans le menu de gauche, le mot "Call for paper" est utilisé et lorsque l'on clique dessus, le mot "Proposals" est utilisé. 

Il faut mettre en cohérence les 2. Il me semble qu'il faut mettre Proposals car pour moi, le CFP est le site pour soumettre les talks et ensuite, nous sommes dans la revue des talks, donc nous avons des propositions à relire, donc des "proposals".

PJ par mail...

**Comment by bpetetot** [comment]
![image](https://user-images.githubusercontent.com/516360/36903481-22b493fa-1e2e-11e8-9f58-8927b5dcc008.png)
