### ISSUE TITLE
[speaker] I would like to add my speaker references into my profile

### ISSUE THREAD

**Issue by Okazari** [bpetetot/conference-hall-beta#245]
Hey !

I'm just wondering, i would love to add my speaker references into a centralized space (in the profile ?) so that i can keep the space "References" in a talk juste to references specific to that talk.

What do you think ? I don't know if speaker references are that usefull anyway.

Tell me ;)

**Comment by bpetetot** [comment]
Yes good idea, I take it.
On the profile page, you will have "Speaker references"
On the talk page, you will have "Talk references"

I renamed the issue title
