### ISSUE TITLE
[speaker] add information on the "References" section

### ISSUE THREAD

**Issue by jlandure** [bpetetot/conference-hall-beta#247]
May people ping me to know what to describe in the "references" section. It should be explicit:
- keywords
- speaker XP: talks, videos...
- info on the prez: slides, livecoding, github repo, video, summary, steps of the talk
In fact, it's all the information the speaker can describe to make him/her selected by the commitee 😅

**Comment by marcpoppleton** [comment]
I thought it was References like the ones when you write a paper, aka bibliography :-D

**Comment by bpetetot** [comment]
Indeed it's confusing.

I think, there are 2 ways to explain it better:
1. Add some tooltips / explanations about what is the purpose of the field
2. Split "Speaker references" (in the profile, so no need to repeat it in each submission) and "Talk references" (in the talk) (see https://github.com/bpetetot/conference-hall/issues/245)
