### ISSUE TITLE
Contributors link broken on public page

### ISSUE THREAD

**Issue by nlepage** [bpetetot/conference-hall-beta#276]
On a public page such as `/public/event/{id}` the contributors link (in the avatar dropdown) is broken.
Being neither in a `/speaker` or `/organizer` subroute, the `baseRoute` resolves to `/`, hence the `href` of the contributors link resolves to `//contributors` interpreted as `https://contributors`

**Comment by nlepage** [comment]
I could write a PR to have `href="/public/contributors"` and change router config consequently, is it OK?

**Comment by bpetetot** [comment]
Yes ! Thanks
