### ISSUE TITLE
Send a mail to organizers when a new proposal has been submitted

### ISSUE THREAD

**Issue by frinyvonnick** [bpetetot/conference-hall-beta#348]

**Comment by bpetetot** [comment]
Must be opt-in the event configuration page

**Comment by bpetetot** [comment]
**Send an email to organizers when:**
- A speaker has sent a proposal
- A speaker has confirmed a talk after acceptation
- A speaker has declined a talk after acceptation

**Must be opt-in the event configuration page**

### To do after PR #343 was merged
