### ISSUE TITLE
Import existing profile from another conference-hall instance

### ISSUE THREAD

**Issue by charlyx** [bpetetot/conference-hall-beta#362]
I'm submitting to different CFP's and some are running their own instance of conference-hall.
Then I have to create a new profile on each instance.

Would it be possible to import a profile from an existing instance? For instance, the "main instance" conference-hall.io? Otherwise, do you think there could be a system to centralize profile somewhere so conference-hall instance could sync with?

These are suggestions, I'm not telling you how to handle it or if you should. But it would be a nice feature to offer speakers 😄 

Happy to discuss! 💬 
And why not proposing a PR later on 😉 

PS: Great job! 😘

**Comment by bpetetot** [comment]
Thanks for the feedback, but the main goal of conference-hall, is to have a unique instance for now. Maybe we could discuss later about a decentralized platform.
Conference-hall opens the platform few month ago, and events have created their own instance before the opening. But at the end "There will only be one" ;)
