### ISSUE TITLE
[organizer] allow invited people to review talks but not access organizer features

### ISSUE THREAD

**Issue by ndeloof** [bpetetot/conference-hall-beta#368]
To ensure quality of proposal review we'd like to get more people involved, without granting hundred people access to our backend. Devoxx'CFP offers a comparable a "golden ticket" feature.

The idea is to have a custom profile which let some user connect to event's backend, see proposals, rate them, but not have access to organizer's features (approve speakers, view global rates, etc)

**Comment by bpetetot** [comment]
## What to do

In an organization, be able to have different roles:
- owner: by default, the creator of the organization
- member: can manage organization events
- reviewer: can only access to proposals list and some features in it.

### Permissions by roles

**Owner:** 
- Can manage organization
- Has all events permissions
- Has all proposals permissions

**Member:** 
- Can only leave the organization
- Has all events permissions
- Has all proposals permissions

**Reviewer:**
- Can only leave the organization.
- Has access to event's proposals and can only vote and see organizer thread.

### Technical tasks
- Add Firestore rules tests for organization
- Add Firestore rules tests for events
- Define the Firestore model to manage organization roles ??? (think abour future improvements like roles by event): https://firebase.google.com/docs/firestore/solutions/role-based-access
