### ISSUE TITLE
[organizer] show comparable proposals

### ISSUE THREAD

**Issue by ndeloof** [bpetetot/conference-hall-beta#370]
On large event there might be many proposal for comparable topics, and it's hard to offer an homogeneous level of analysis when rating them at distinct times.
Would be nice to get comparable proposals (based on keywords or text analysis ?) listed aside proposal one is currently reviewing, so it's easier to review them with an homogeneous criticism level :)

**Comment by martinbonnin** [comment]
+1. I'd love private tags for this. As we go, we could create tags (`green IT`, `accessibility`, `kubernetes`, ...) and bucket the talks to make a 2nd pass for all talks in a given bucket.
