### ISSUE TITLE
Possility to search by any fields

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#427]
Right now, it is only possible to do a search by the title of a conference. 
We can maybe improve this feature, and add the ability to search by other fields. 

In the screenshot below, I am doing a search by the speaker thanks to a `speaker` prefix. 

What do you think ? @bpetetot 

![image](https://user-images.githubusercontent.com/555768/50735055-97c5a080-11a8-11e9-8f82-613464441e70.png)

**Comment by bpetetot** [comment]
Yes It's good idea, I would like to do that, but the full text search are not supported by Firestore for now. Another solution could be to use Algolia, but it seems quite expensive.

I'm still looking for a cheaper solution, do you have any idea ?

**Comment by EmmanuelDemey** [comment]
Maybe a partnership with Algolia ?

**Comment by bpetetot** [comment]
Indeed it seems possible: https://www.algolia.com/for-open-source
I'm going to investigate. Thanks ;)
