### ISSUE TITLE
contributing guide

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/conference-hall-beta#43]
# Contributing

Contributions, issues and feature requests are very welcome. If you are using this app and fixed a bug or improve it, please consider submitting a PR! Also you can ping me at [Twitter](https://twitter.com/bpetetot)

### General guidelines

- The master branch is where incoming new features are merged (the next coming release).
- The production branch is a snapshot of the latest stable release.
- All hotfix should be done in dedicated branch from the `production` branch.
- All new features / bugs should be done in dedicated branch from the `master` branch.
- It's a very nice thing to have multiple small commits as you work on the PR. It's easier to review it. Then we will squash it before merging.

### Commit messages

// explain it here
https://gitmoji.carloscuesta.me/

### Adding new feature

Provide convincing reason to add this feature. Ideally you should open a suggestion issue first and have it green-lighted before working on it.

### Pre-requisites
- `node`
- `yarn`

### Install 

[Follow instructions into the README.md file](http://todo)

### Developing

// project structure
// main used libraries
// wiki

## Contributors

// Add list here

**Comment by martinbonnin** [comment]
Is this up-to-date ? It looks like there's no develop branch anymore ?

**Comment by bpetetot** [comment]
This is not up-to-date, this issue is a work in progress to defined the contribution guide.

This is how it is today:
- The `master` branch is where incoming new features are merged (the next coming release).
- The `production` branch is a snapshot of the latest stable release.

I change it in the issue, thx 😉
