### ISSUE TITLE
Pourquoi maps.googleapis.com est appelé au chargement de la page d'accueil ?

### ISSUE THREAD

**Issue by gmembre-zenika** [bpetetot/conference-hall-beta#444]
Lors du chargement de la page d'accueil sur la TZ nantes, il y a plusieurs requetes sur  l'api gmaps alors qu'il n'y a pas de carte affichée.

![image](https://user-images.githubusercontent.com/7294764/51180649-2cc34a80-18c9-11e9-9ef9-97dbbdb6b333.png)

**Comment by jlandure** [comment]
Hey @gmembre-zenika 👋 
> Why conference-hall make some calls to `maps.googleapis.com`?

On an event, conference-hall displays a map with the location of the event. Gmaps is used to get the location from the address. For example:
<img width="1198" alt="capture d ecran 2019-01-28 a 20 56 04" src="https://user-images.githubusercontent.com/525974/51862698-75561b80-233f-11e9-9698-bb103c393ea5.png">

**Comment by gmembre-zenika** [comment]
On the initial conference (tz de l'ouest), there were no maps displayed, so I do not expect calls to maps.gogl...

**Comment by bpetetot** [comment]
Indeed, it seems that it downloads google maps javascript lib too early, it should be more optimized to load it only when needed (but the map loading will take more time)
I will check what's the best way to load it.
