### ISSUE TITLE
Submit a talk does not allow to submit

### ISSUE THREAD

**Issue by pilhuhn** [bpetetot/conference-hall-beta#450]
it only lists the already submitted talks.
I have to go to "my talks" to submit a 2nd one
<img width="1348" alt="bildschirmfoto 2019-01-24 um 11 53 02" src="https://user-images.githubusercontent.com/208246/51673592-a5638e80-1fce-11e9-8c2c-9b05a306caa1.png">

**Comment by bpetetot** [comment]
Thanks for the feedback, indeed, there are some UX issues, we are working on it with the issue #439
I close this one, you can follow the discussion in #439 if you want. thanks again ;)
