### ISSUE TITLE
[organizer] Sort by "newest" doesn't work

### ISSUE THREAD

**Issue by jlandure** [bpetetot/conference-hall-beta#451]
The "newest" sort seems to be broken. I saw new talks but the first ones are always the same in the "Proposals"...

**Comment by corinnekrych** [comment]
possible duplicate of https://github.com/bpetetot/conference-hall/issues/416

**Comment by bpetetot** [comment]
Thx for the feedback @jlandure, Indeed closing it because duplicate of #416
PR in progress ;)
