### ISSUE TITLE
Filter selection stay selected under the hood when switching between events. 

### ISSUE THREAD

**Issue by sebastienblanc** [bpetetot/conference-hall-beta#452]
Steps to reproduce : 
I have event A and I filter on conference format "x". I go to event B, even if conference format is on "all" it is still keeping filtering on format "x". This can be really confusing and I think it's a simple frontend issue.

**Comment by corinnekrych** [comment]
@bpetetot i think this is more a 🐛 than a feature....

**Comment by bpetetot** [comment]
Indeed it's a bug :P thanks for the feedback
