### ISSUE TITLE
User feedback on flow

### ISSUE THREAD

**Issue by emmanuelbernard** [bpetetot/conference-hall-beta#453]
Hi, I've been using conference-hall for RivieraDev and RivieraDev JUDCon. Feel free to ignore but @corinnekrych recommended I give my feedback.

I do like the idea of me as a speaker being able to get a list of talks for various conferences. Today I use Evernote to keep track of them. But I have been confused by Conference Hall implementation.

When I submit the same talk to two conferences, I often change it at the margin (size limits, better tailored for the conference, improvement over time etc). So the pool of talks should be loosely coupled with the actual version submitted.

The other big hurdle I had is that I wanted to write my proposal, submit and later add speakers. Finding speakers by email is really non practical as it requires me to pre-coordinate with my co-speaker to make sure he has submitted and also to give me the actual email address he has used. Two times I had to do a weird submission cancellation back to some edit mode to add the speaker and then submit this new talk.

As you can gather, there might be a clear workflow between talks and submissions and when to edit which but it is all opaque to me and I could not figure it out.

The last hurdle is that I cannot see in one page all my submitted talks to all conferences. You have a page per conference and it is hard to find how to reach it.

**Comment by bpetetot** [comment]
Thanks for the feedbacks! We are thinking and working about a new UX, your feedbacks will help a lot.

Quickly, just for the co-speaker hurdle, It's not obvious today, but you can send an invite link for a talk to your co-speaker. When you click "add a co-speaker", you have the choice between searching by email or copying the invite link. Then, you juste have to send this link to your co-speaker. When your co-speaker will click on the link, he will be invite to sign in to "Conference Hall" and finally will automatically be a co-speaker for your talk.

Another things seems unclear in the app UX, but once you have submitted a talk, you can always update it until the CFP is closed. It means that you can add a co-speaker, change the abstract or the references... then you just have to submit it again and it will be updated. (you dont have to do submission cancellation)

**Comment by bpetetot** [comment]
Closed because these UX issues will be worked and discussed in issue #439
