### ISSUE TITLE
[speaker][organizer] As a speaker, I can't see the conference I've created

### ISSUE THREAD

**Issue by Riduidel** [bpetetot/conference-hall-beta#454]
I have created an organization, "Zenika Lile", to which I've attached a conference : "Technozaure lille mars 2019".
I alos have created a talk, which I want to submit to this conference CFP. Unfortunatly, this conference is not visible in the list I get as a speaker. I would have loved to give you more details, but it seems like firestore returns results in a way I don't understand :-o

**Comment by Riduidel** [comment]
Sorry, I didn't saw there was specific section for private conferences

**Comment by bpetetot** [comment]
Yes when you set a private conference, you must get the share link on "Event profile" page, then you can share this link and people will be able to access it.
