### ISSUE TITLE
[organizer] Filter event talks proposal by speaker name

### ISSUE THREAD

**Issue by qboileau** [bpetetot/conference-hall-beta#463]
Currently talk list only search filter only works on talk name. 
It could be useful to find all talks of a specific speaker (or find if a speaker already sumbit a talk).
We could also filter on company name but I'm not sure it would be useful.

**Comment by frinyvonnick** [comment]
Thanks for the feedback. It is currently done by the PR #449

**Comment by qboileau** [comment]
Ok nice :+1: , I had searched on issues list but I had not seen issue https://github.com/bpetetot/conference-hall/issues/427 sorry.
