### ISSUE TITLE
Add help for the references textarea

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#469]
A lot of people ask me : what should I put in this area ? My previous talks ? some youtube videos about this talks ? a message to the organizers ? ...

Maybe we can some help on this form in order to help new speakers ? What do you think ?

![image](https://user-images.githubusercontent.com/555768/52717546-a1a9a300-2fa1-11e9-9883-c3136ef2ada9.png)

**Comment by bpetetot** [comment]
Yes indeed there is something to do about reference fields.
I already have 2 issues about it #247 and #245, so if it's good for you I close this one.
