### ISSUE TITLE
[organizer] Accept or reject and proposal without sending email

### ISSUE THREAD

**Issue by frinyvonnick** [bpetetot/conference-hall-beta#479]
I would like the possibility to accept or reject a talk without sending an email. Sometimes we already took contact with the speaker through twitter (for example).

**Edit:**
After discussion with @bpetetot we can disable the sending mail feature for meetup by default. Then we will add an option in event page to send mail on status change.

**Comment by bpetetot** [comment]
Done in #559 
Now sending email is a separated action (under "actions..." button)

**Comment by frinyvonnick** [comment]
Saw that, really nice @corinnekrych it helped us a lot at @NantesJS, Thank you 🙏
