### ISSUE TITLE
Login avec twitter and github ne fonctionne pas

### ISSUE THREAD

**Issue by boillodmanuel** [bpetetot/conference-hall-beta#481]
La popup se ferme et puis rien. A noter que je me suis connecté une première fois avec google.

Ensuite en navigation privée ou avec un autre navigateur, le login twitter ou github ne fonctionne pas

**Comment by bpetetot** [comment]
Merci pour le retour manu, est ce que tu as des messages d'erreur dans ta console ?
Tu utilises quel navigateur ?
Merci ;)

**Comment by boillodmanuel** [comment]
J'utilise opéra, mais j'ai testé avec chrome également.

Voici la trace : 
```js
Authentication error :
{
code: "auth/account-exists-with-different-credential"
credential: Di {a: null, accessToken: "HIDDEN", providerId: "github.com", signInMethod: "github.com"}
email: "xxx@gmail.com"
message: "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address."
}```

**Comment by bpetetot** [comment]
En effet, le login ne peut se faire que pour une adresse email et un seul provider.
Comme le process pour lier un nouveau provider à une email adresse existante (fournie par un autre provider) est un peu fastidieux à implémenter, j'ai (pour le moment) juste afficher le message d'erreur pour que l'utilisateur voit qu'il y a une erreur et qu'il doit choisir un autre provider.
