### ISSUE TITLE
Permission twitter un peu large

### ISSUE THREAD

**Issue by boillodmanuel** [bpetetot/conference-hall-beta#483]
Demande les permissions suivantes (qui peuvent sembler superflus) :
- Read Tweets from your timeline.
- See who you follow.

Je ne sais pas si on peut limiter au profil

**Comment by bpetetot** [comment]
En effet ce n'est pas nécessaire, je vais regarder ça merci.Ce sont les permissions par défaut de l'authentification twitter via Firebase, j'espère qu'ils permettent de les diminuer.

**Comment by bpetetot** [comment]
J'ai regardé en détail les scopes de permission pour l'authentification twitter, il s'agit bien du minimum possible en read-only :( Je ne peux pas faire moins
