### ISSUE TITLE
[organizer] visual misplacement in the various talk badges

### ISSUE THREAD

**Issue by Riduidel** [bpetetot/conference-hall-beta#491]
Seems like there is a small layout bug on organizer panel when there are many badges displayed

![image](https://user-images.githubusercontent.com/171018/53649497-9366b280-3c42-11e9-9c4d-790798583e4d.png)

Obtained with Firefox 65.0.2 on Windows

**Comment by Riduidel** [comment]
it seems that badges trigger the enlarging of the dropdown list

![image](https://user-images.githubusercontent.com/171018/53649590-c315ba80-3c42-11e9-95de-8cc3d53ba317.png)

**Comment by bpetetot** [comment]
Thanks for the feedback 👍 we will fix that
