### ISSUE TITLE
Logout feature for mobile

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#492]
Give the possibility to users so logout when using conference hall with a mobile.

**Comment by tbetous** [comment]
Here is my humble suggestion about this issue. Why would we not reuse AvatarDropDown component in Brand component when we are in mobile mode. What do you think about this ?

Here is a prototype :

![example](https://user-images.githubusercontent.com/4435536/54564248-9c3ddf00-49cb-11e9-9be3-819da2404c8e.gif)

**Comment by bpetetot** [comment]
Yes great idea, seems good to me 👍
