### ISSUE TITLE
[organizer] provide a way to do bulk email sending for proposal

### ISSUE THREAD

**Issue by corinnekrych** [bpetetot/conference-hall-beta#508]
It would be nide for the organizers to be able to send a batch of email at the same time for those proposals that have not been selected.
- in the UI provide a mail to select all proposal and a action to send email a bit like Gmail:
![ljw_qkR8](https://user-images.githubusercontent.com/1395710/54489095-0ad64c00-48a9-11e9-9bbb-2f26aebb3007.png)
- work around some mailgun free account limitation:
```
You are sending too fast
--
Your account is on probation and domains are limited to 100 messages / hour. To maintain the rate the account has been temporarily disabled.The account will be enabled in 1759 seconds.Thank you,Mailgun Team 
```

**Comment by bpetetot** [comment]
Done in #559
