### ISSUE TITLE
[organizer] Manage different organizer roles

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#532]
As an admin, we can add new people to the organizers team. But we cannot remove them. We should add this possibility. 

![image](https://user-images.githubusercontent.com/555768/55883541-ce93c400-5ba6-11e9-9a42-09d553ab0520.png)

**Comment by bpetetot** [comment]
You should able to do it if you are the creator of the organization.

**Comment by EmmanuelDemey** [comment]
You are right. Maybe we can keep this issue somewhere, when multi roles will be available ? 
- [ ] admins can remove people
- [ ] reviewers cannot

**Comment by bpetetot** [comment]
Yes we should keep it. Can you change the issue title by: "Manage different organizer roles"
I see 3 roles:
- **Owners:** has full privileges on the organization and events
- **Members:** has no privileges on the organization but full privileges on events
- **Reviewers:** has no privileges on the organization and can only review proposals

What do you think about that ?

**Comment by bpetetot** [comment]
Closed in favor of the related ticket #368
