### ISSUE TITLE
HTTP link in the "Talk accepted" email

### ISSUE THREAD

**Issue by EmmanuelDemey** [bpetetot/conference-hall-beta#539]
One of our speaker share this issue. On the "Talk accepted" email, the link to conference hall was is HTTP.  The page was blocked by the browser. 

<img width="1428" alt="Capture d’écran, le 2019-04-15 à 08 37 15" src="https://user-images.githubusercontent.com/555768/56111916-c39bb380-5f59-11e9-83da-214a19ae9396.png">

**Comment by bpetetot** [comment]
Thanks for the feedback, I'm going to check this.
cc @jlandure

**Comment by bpetetot** [comment]
Also change the mailgun address:
`http://email.mg.gdgnantes.com`
to this kind:
`https://email.mg.conference-hall.io` (dont forget https)

cc @jlandure

**Comment by bpetetot** [comment]
Also we have to configure delivered email through mailgun web hooks:
see https://github.com/bpetetot/conference-hall/blob/master/docs/app/installation.mdx#configure-mailgun-webhook-optional

Also have to configure "Authorized Recipients" to the sandbox for testing purpose:
https://help.mailgun.com/hc/en-us/articles/217531258

cc @jlandure

**Comment by bpetetot** [comment]
All fixed, thanks @jlandure
