### ISSUE TITLE
[organizer] dépouillement papier

### ISSUE THREAD

**Issue by ndeloof** [bpetetot/conference-hall-beta#548]
sur cfp.io nous avons mis en place la génération de fiches papier via un export PDF des proposition, ce qui permet des échanges très efficaces lors du dépouillement.
Nous avons aussi un canevas du programme.
En fin de dépouillement, un scan des codes barres sur chaque fiche+canevas remplis le schedule de la conférence en qq minutes

**Comment by bpetetot** [comment]
Ca m'a l'air très pratique comme principe mais je ne comprends pas comment tu fais le lien entre le code bar de la fiche et sur quel slot du programme il sera affecté pour le schedule.

**Comment by bpetetot** [comment]
Now you can print the proposals from PDF cards export. (but the whole bar code system is not done yet)

![image](https://user-images.githubusercontent.com/516360/69480392-51505300-0e07-11ea-8b21-7b3d72c89824.png)
