### ISSUE TITLE
Nom prénom non affichés

### ISSUE THREAD

**Issue by Zorkbomb** [bpetetot/conference-hall-beta#570]
Bonjour,

Mon "nom-prénom" de profil ne sont pas récupérés correctement de mon profil Github ... J'apparais "[NULL]" dans le profil et dans les classement de votes des présentations  :'-(

Help meeeee pleaze.

Bonne journée à l'équipe !

**Comment by bpetetot** [comment]
The correction will be done in ticket #598. With the next release. It should be ok when you will reconnect to conference hall. 
So I closed it in favor to #598 Thanks ;)
