### ISSUE TITLE
[organizer] Send explanation with rejected proposal

### ISSUE THREAD

**Issue by vogloblinsky** [bpetetot/conference-hall-beta#584]
As a speaker, i am always frustrated when i got an email with a rejected proposal with no explantion of the "why" ?
It could help a lot the spearkers who sometimes send the proposal to multiple CFP.
May be an internal comment for the organizers, and a "speaker" one could be enough. The "speaker" one will be send with the rejected email.

**Comment by bpetetot** [comment]
Hi @vogloblinsky, thanks for your feedback.
I'm agree with you it could be very helpful to have explanation about a rejection. But as organizer, we have almost 400 to 600 proposals to review, and it's impossible to send a feedback for each proposal in emails, we would spend hours to do it.
But another solution could be in the issue #358, so you could ask to organizer why your talk as been rejected.
What do you think about it ?

**Comment by vogloblinsky** [comment]
Yes i understand the amount of work it requires.
I think as you said, a link in the rejected email to give the ability to ask for feedback could be fine.

**Comment by vogloblinsky** [comment]
@bpetetot we don't have the opportunity to contact organizer after "talk not accepted" to get feedback, is that right ?
I can see related feature here https://github.com/bpetetot/conference-hall/issues/358
Thanks

**Comment by bpetetot** [comment]
Not done yet indeed but you can send an email to organizers through the 'contact email' on the event page and ask more info

**Comment by bpetetot** [comment]
I close this ticket, I have added your comment in the issue https://github.com/bpetetot/conference-hall/issues/358#issuecomment-515623162

Thanks for the feedback
