### ISSUE TITLE
[speaker] cannot change my nickname after Google Login

### ISSUE THREAD

**Issue by yannick-milanetto** [bpetetot/conference-hall-beta#593]
Hi,

I've edited my Google profile name, after registering on Conference Hall (via Google), but it doesn't get updated on my Conference Hall's profile.
I tried to find a way to edit the name directly on my profile page, but it seems this option is not available. How can i do ?

Thanks in advance.

**Comment by bpetetot** [comment]
This is a bug, we will fix it asap. Thanks for the feedback.
Linked to #598

**Comment by bpetetot** [comment]
Done in #623. Will be in production soon
