### ISSUE TITLE
Explanation of "reference" and "Message to organizers"

### ISSUE THREAD

**Issue by gmembre-zenika** [bpetetot/conference-hall-beta#594]
Could you please provide an explanation of the field "Reference" and "Message to organizers" please ?

**Comment by bpetetot** [comment]
Add a tooltip to "Message to organizers" in the submission process to explain what is expected in this field.

**Example:**
Add a message to organizers to ask special requirements or just thanks them for the event ;)

_(already done for "Reference" field when you edit a talk)_
