### ISSUE TITLE
[organizer] export comments from organizers thread

### ISSUE THREAD

**Issue by joow** [bpetetot/conference-hall-beta#616]
For our deliberation process we are using Trello boards, populated using the export from the CFP.

We'd like to add as comments to the Trello cards the comments made by organizers in the organizers thread.
Ideally for each talk the text and the timestamp of each comment would be exported (allow for easy comment sorting by date).

**Comment by bpetetot** [comment]
Thanks for the feedback, the PR of @brunosabot  seems good. So it will be in the next release in the coming weeks.
