### ISSUE TITLE
add GitHub issue templates

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/conference-hall-beta#651]
Take a look to this one
https://github.com/nock/nock/tree/beta/.github/ISSUE_TEMPLATE

**Comment by frinyvonnick** [comment]
Did you see that too https://saythanks.io/ ?

**Comment by bpetetot** [comment]
Seems cool, but here I'm interested by Issues, Feature Requests and Ideas as templates:
![image](https://user-images.githubusercontent.com/516360/62410787-4de05400-b5eb-11e9-878f-75ebd4b4ace3.png)
