### ISSUE TITLE
[organizer] Add POST endpoint to accept/refuse/set as backup proposals

### ISSUE THREAD

**Issue by joow** [bpetetot/conference-hall-beta#657]
**Description**

It would be nice to have an endpoint allowing an organizer to set a proposal as accepted, backup or refused.  
This would allow us to automate entering the results of the deliberations back into Conference Hall.

**Comment by bpetetot** [comment]
Good idea, I will plan it in a future release

**Comment by bpetetot** [comment]
✨Accept and Reject endpoint done by @brunosabot 
Here the documentation:
https://contribute-conference-hall.netlify.com/?path=/docs/apis-proposals--page

Backup endpoint will be done with #503 issue
