### ISSUE TITLE
[export] Add proposal id in export

### ISSUE THREAD

**Issue by joow** [bpetetot/conference-hall-beta#658]
**Description**

The JSON exported does not contain the id for the proposals, whereas the API endpoint does.  
As we're using another tool for our deliberations it would be nice to have the id of the proposals in the export, as it allows us to create a link to the proposal in Conference Hall in our deliberations tool.

**Comment by bpetetot** [comment]
Yes it's easy to do and could be quick. Thanks for the feedback
