### ISSUE TITLE
[organizer] Limit choices for language

### ISSUE THREAD

**Issue by joow** [bpetetot/conference-hall-beta#659]
**Description**

A field has been added to allow speakers to set the language of their proposal (can be used when generating the program).  
Unfortunately as the field is free we got a lot of different values for the same languages and also some unrelated data (some programming languages for examples :sweat_smile:).

It would be better to either :
- allow organizers to specify valid values
- propose only valid languages, using for example [ISO 639](https://en.wikipedia.org/wiki/ISO_639) list of languages (alpha-2 and alpha-3 codes)

**Comment by bpetetot** [comment]
Indeed we had the same issue (some programming languages) with the DevFest Nantes.
I think the best way it to set pre-defined language list (like ISO 639).
This list of languages seems great: 
https://github.com/umpirsky/language-list/blob/master/data/en_US/language.json

*work to do:*
- change the input text by an input select
- load the language list as options of the select
- the language list will be statically imported
