### ISSUE TITLE
Rejection emails rejected due to inexistant domain name mg.conference-hall.io

### ISSUE THREAD

**Issue by jooooooon** [bpetetot/conference-hall-beta#661]
Hi there!

We (the devops REX conference) are using conference-hall.io as a SaaS platform to manage our CFP this year. I've encountered a specific bug where I never recieve the emails sent by the platform. This is the Postfix error message:

`Aug 26 13:48:42 XXXXXXXX postfix/smtpd[1866]: NOQUEUE: reject: RCPT from m42-1.mailgun.net[69.72.42.1]: 450 4.1.8 <bounce+89f10a.ba0bf3-cfp=devopsrex.fr@mg.conference-hall.io>: Sender address rejected: Domain not found; from=<bounce+89f10a.ba0bf3-cfp=devopsrex.fr@mg.conference-hall.io> to=<cfp@devopsrex.fr> proto=ESMTP helo=<m42-1.mailgun.net>`

It looks like you should either create a DNS record for mg.conference-hall.io or use a sending domain that already exists.

Thanks and keep up the good work!

**Comment by bpetetot** [comment]
Hi, thanks for the feedback.

Is it happening for all emails ?

When I check stats in mailgun dashboard I have:
- 362 delivered the Aug 25
- 44 delivered the Aug 26 but 8 with status `bounced`

Is it what you sent ?

I'm going to check that.

**Comment by jooooooon** [comment]
Hi, sorry for the slow reply, I had filtered GitHub emails to a folder I never read a bit too agressively :-)

I doubt we've sent as many emails. Unless the platform automatically sends emails on new proposals, or something similar?

But I just checked our mail server logs and this is still happening:
```Sep  5 17:17:41 XXX postfix/smtpd[7885]: NOQUEUE: reject: RCPT from rs238.mailgun.us[209.61.151.238]: 450 4.1.8 <bounce+5500fc.ba0bf3-xxx.xxx=xxx.com@mg.conference-hall.io>: Sender address rejected: Domain not found; from=<bounce+5500fc.ba0bf3-xxx.xxx=xxx.com@mg.conference-hall.io> to=<xxx.xxx@xxx.com> proto=ESMTP helo=<rs238.mailgun.us>```

My email address is my firstname.lastname so you can search on that if you'd like. I've blanked it here for obvious reasons.

**Comment by HugoGresse** [comment]
I've created a new issue here: https://github.com/bpetetot/conference-hall/issues/921 
Adding MX record and dmarc should be mostly enough?

**Comment by bpetetot** [comment]
Should be good with MX records and dmarc added (see https://github.com/bpetetot/conference-hall/issues/921)
