### ISSUE TITLE
Missing submit button on mobile event page

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/conference-hall-beta#667]
**What is the issue?**
https://twitter.com/AntoineAugusti/status/1168806224399425536

**Comment by lhoang** [comment]
the button shows up in landscape mode but disappear in portrait mode (on iphone 6S).

Maybe the missing button is on purpose ? 
https://github.com/bpetetot/conference-hall/blob/master/src/screens/components/event/banner/banner.jsx#L24
