### ISSUE TITLE
Retrieve Organizers thread from API

### ISSUE THREAD

**Issue by Ldoppea** [bpetetot/conference-hall-beta#668]
**Description**

Hi,

First, thank you for letting us access your Beta program for our event.

When using our old CFP tool, my team used to add some tracking flags in organizer comments so we were able to retrieve them and see them using a [custom tool](https://github.com/Ldoppea/snowcamp-papercall-helper).

But the Conference-Hall `event/` api does not include the organizers thread. So we cannot use this mechanism. Would it be possible to implement this feature?

This would be very powerful for us to "implement" missing features without having to wait for future releases. For sure we would be happy to share with you which features we had to implement in our tool so you can think about adding them natively or not.

For example we used the following flags :
`Warning:` add a red warning area under the talk with the comment content (ex: this talk have requirements for network opened ports)
`PreviousTalk:` allow to add a link reference to a video talk from the speaker.

`Category:` would allow us to add a category to the talk when the speaker forgot to add one (while waiting for your future update that add the ["mandatory" option](https://github.com/bpetetot/conference-hall/issues/646) ❤️ )
`EmailSent` would allow us to track when we contacted speakers by email

**Additional context**

This feature may be related to this one that added Organizers thread to the export feature : https://github.com/bpetetot/conference-hall/issues/616

Also, right now I expect to use the export link using my private bearer to do that automatically. Would you agree with that?

**Comment by bpetetot** [comment]
Hello, sorry for the delay I was very busy with the Devfest Nantes organization, but I'm back.
First thanks for all these ideas and feedbacks, lot of good ideas.

About the ideas:
- Add tags with comment to proposals: this is a great idea. **Issue created: #716**
- Add a category: already have an issue about it and it will be in the next roadmap (#633)
- EmailSent: today you can send email through conference hall and you see if the email has been sent or not

Considering this issue "Add threads into API", we dont want to do it to avoid that some private comments between organizers could be visible if the API key has been leaked. (that why you cant access to private speaker info from the API today). But you can use the export link using your private bearer to do that automatically.

I close this issue in favor of #716 and #633 
Thanks ;)
