### ISSUE TITLE
[organizer] Organizers are sorted randomly in organization

### ISSUE THREAD

**Issue by Riduidel** [bpetetot/conference-hall-beta#669]
In private organizations, when showing the details of an organization, we get the list of organizers.
In this screen, organizers are not sorted in any way (I suggest sorting by last name/first name).
Beside, there is no way to search a user by any means.

**Comment by bpetetot** [comment]
Indeed, there is no sort applyied to this list. Sorting by names seems a good idea. We also can add a quick search to this list. Thanks for the feedback.
