### ISSUE TITLE
Authentification + GitHub et "Keep my email addresses private"

### ISSUE THREAD

**Issue by thom4parisot** [bpetetot/conference-hall-beta#671]
Hello,

J'utilise la fonctionnalité "Keep my email addresses private" sur GitHub, et j'ai utilisé GitHub pour m'identifier comme speaker. Si on m'envoie un email, je ne peux pas le recevoir, de fait.

![image](https://user-images.githubusercontent.com/138627/65310537-d496c380-db8e-11e9-8bb5-ef3e7a5697fe.png)

Est-il possible de personnaliser l'email (et/ou d'être invité·e à indiquer un email pour communiquer entre organisateurices et speaker) depuis l'interface de Conference Hall ?

**Comment by bpetetot** [comment]
Merci pour le retour, en effet c'est problématique. Pour le moment, ce n'est pas possible de modifier son email, mais nous allons faire en sorte de corriger ça rapidement pour pouvoir le modifier dans la page de profil.
