### ISSUE TITLE
Impossible de rejoindre l'organization

### ISSUE THREAD

**Issue by YanisBou** [bpetetot/conference-hall-beta#684]
Quand je clic sur "Join Organization" rien ne se passe. Si ja vais dans le menu "My Organizations", je vois apparaitre pendant une fraction de seconde Zenika puis l'organization disparait et "No organization yet!" s'affiche.

**Comment by frinyvonnick** [comment]
Le lien d'invitation a été temporairement désactivé. Il faut inviter les membres d'une organisation unitairement en attendant 😄 Désolé pour le désagrément.

**Comment by bpetetot** [comment]
Les liens d'invitations sont revenus ;) Par contre, ils nécessitent d'être regénéré. (PR #739)
