### ISSUE TITLE
[speaker] profile picture is not taken google account

### ISSUE THREAD

**Issue by julien-topcu** [bpetetot/conference-hall-beta#727]
**What is the issue?**

My conference-hall profile doesn't have any picture although I have one configured with the google account I'm using

**What is the expected behavior?**

Google account profile picture should be used

**Comment by bpetetot** [comment]
Thanks for the feedback. It seems it happens sometimes, I can't figure out why :( I'm not able to reproduce it.
I'm going to give the ability to change the avatar URL in the profile page, to fix this kind of issue.

**Comment by julien-topcu** [comment]
Thank you for your feedback 🙂
