### ISSUE TITLE
As reviewer, I want to communicate with my follow reviewers on a talk

### ISSUE THREAD

**Issue by rlespinasse** [bpetetot/conference-hall-beta#766]
**Description**

A reviewer can't see and use the `organizers thread` during the vote of one talk.

Can we enable the reviewer role to read and write on it.
In addition, maybe we can rename this thread as `reviewers thread`.

**Comment by bpetetot** [comment]
Yes indeed, it's a good idea. Thanks for the feedback, we will do it asap.

**Comment by bpetetot** [comment]
Instruction for the contributor that will do it:
- Move `<OrganizerThread>` component out of `<HasRole>` component:
https://github.com/bpetetot/conference-hall/blob/6e37cf1cc665aed8663e727fb1cb6169c7b78162/src/screens/organizer/proposal/actions/actions.jsx#L16-L26
- Change labels and names (also filenames) from organizer thread to reviewer thread:
https://github.com/bpetetot/conference-hall/tree/master/src/screens/organizer/proposal/actions/organizersThread
