### ISSUE TITLE
README.md contribution link, should redirect to the Contributing Page

### ISSUE THREAD

**Issue by es-rene99** [bpetetot/conference-hall-beta#837]
**Description**

The" You want to contribute?" link redirects to the Home Page, when I believe it would be a better UX to redirect to the Contributing Page.

**Additional context**

"You want to contribute" link: https://contribute-conference-hall.netlify.com
redirects to Home page: https://contribute-conference-hall.netlify.app/?path=/docs/documentation-home--page
but I suggest there should be a label that redirects instead to:  https://contribute-conference-hall.netlify.app/?path=/docs/documentation-contributing--page 

It could be like: 

"If you want to contribute and make **Conference Hall** better, [go here.](https://contribute-conference-hall.netlify.app/?path=/docs/documentation-contributing--page)"

**Comment by bpetetot** [comment]
Thanks for the feedback, it's a great idea

**Comment by es-rene99** [comment]
Glad to hear! I will submit pull request shortly
