### ISSUE TITLE
Proposal export is empty after CFP is closed

### ISSUE THREAD

**Issue by Riduidel** [bpetetot/conference-hall-beta#846]
In order to organize my conference, I want to export the proposals after CFP end (and after my colleagues have voted).
But since the CFP is closed, it seems like conference hall produces an empty export.

**Comment by bpetetot** [comment]
Thanks for the feedback @Riduidel 
I think it's a regression, I'm going to fix it quickly

**Comment by bpetetot** [comment]
@Riduidel It's fixed ;)

**Comment by Riduidel** [comment]
You know you have the right to take week-ends 🥰😘
