### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by tagazok** [bpetetot/conference-hall-beta#851]
**What is the issue?**
The platform is not complient with accessibility standards.
ex :
 - on an event page, the "submit talk" button is never focus when using a keyboard (therefore a screen reader)
 - on the page where my talks are listed, same, only the top and left menus are focusable, not my list of talks.

**What is the expected behavior?**
Be able to use a the platform with a screen reader

**What is your environment?**
- OS: Windows 10
- Browser: Chrome

**Comment by bpetetot** [comment]
Some accessibility issues fixed in v0.37.0 but need to go further in order to be fully compliant.
