### ISSUE TITLE
Contrast Issues on CFP page

### ISSUE THREAD

**Issue by aardrian** [bpetetot/conference-hall-beta#856]
On the page: https://conference-hall.io/public/event/FdP7ePMBrbLq9kZd4Hye

* The orange background (#FFAB00) and white text (#FFFFFF) combination (the "Conference Hall" brand in the upper left and the "Submit a Talk" button) has a contrast ratio of 1.9:1, where 4.5:1 is needed.
* The green text (#7FBA01) and white-ish background (#EDF2F5) combination ("Call for paper is opened" and "Until December 13, 2020, 5:59 PM EST") has a contrast ratio of 2.1:1. 3:1 is needed for the fake heading because it is larger, but 4.5:1 is needed for the other text.
* The text "AccessibilityCon" and "Conference • France" has contrast issues depending where it overlaps with the background image, so different users in different contexts may struggle.

See WCAG 2.1 Success Criterion [1.4.3 Contrast (Minimum) Level AA](https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum) for more details and guidance.

**Comment by bpetetot** [comment]
Thanks for the feedback and the resource links. It's very useful 🙏
We have checked all color contrasts in the whole app.
So we changed a lot of colors ;) Now color contrasts should meet the Level AA criterion. Thanks again.
Fix: ed87c100143920ff10854fc6e0d5185c2e957ad7
