### ISSUE TITLE
[speaker] review from fabienjuif

### ISSUE THREAD

**Issue by fabienjuif** [bpetetot/conference-hall-beta#87]
All these issues are as a speaker POV.

## Conference page (https:/conference-hall.firebaseapp.com/public/event/cY2n0JuiHrDEYVNe6BIC)
 - URL should be customisable per event (to avoid firebase id)
 - I can't check what is the `talk` format (purpose/time allowed/etc)
![image](https://user-images.githubusercontent.com/17828231/34729182-48dd7862-f55c-11e7-96a3-95747cb55b3d.png)
    * Maybe add information on hover ?

## Profile
 - `FAVORITE LANGUAGE` should be a select box ?
 - Add a feature to see my profile as a reader POV ?
 - Add a feature to change my avatar ?
 - I created my talk, I come back to my list, my talk was not there instantly, maybe add it to store when I create it ?
 - I can't come back to conference

## I come back to conference page
 - I clicked on "submit talk" and I saw "devoxx" for the first time I think
 - The first time I just come back to "home" with the link given on the connection screen
![image](https://user-images.githubusercontent.com/17828231/34729583-63203024-f55d-11e7-933e-cce10c90db46.png)
    * Maybe delete the `back to home` from login page

## I disconnected, then I come back to my talks
![image](https://user-images.githubusercontent.com/17828231/34729665-a159759e-f55d-11e7-8149-95860aa73a45.png)
 - How will you handle multi-conference system with such big buttons ? (`SUBMIT TO DEVOXX FRANCE`)

## I submit `test 2` to **DEVOXX FRANCE**
 - I edited it `test 2 - update`
 - Is my talk edited for **DEVOXX FRANCE** ?
 - Should I submit it again ?
 - How can I fix it for **DEVOXX FRANCE** only ?

## References
 - Are references for my talk or for me ?
 - Why `MESSAGE TO ORGANIZERS` not in common ?
 
## Other
 - I can't set a langage per talk

**Comment by bpetetot** [comment]
all issues has been creates : #92 #93 #94 #95
