### ISSUE TITLE
As a speaker, I don't receive mail when my conf is accepted or declined 

### ISSUE THREAD

**Issue by larousso** [bpetetot/conference-hall-beta#901]

**Comment by jotak** [comment]
+1 same here, my talk was accepted at Sunny Tech 2022 but I didn't receive any confirmation. My co-speaker received it and could forward it to me.

**Comment by bpetetot** [comment]
Thanks for the feedbacks.
Should be good now with MX records and dmarc added (see https://github.com/bpetetot/conference-hall/issues/921)
