### ISSUE TITLE
[BUG] Cannot see proposed meetup

### ISSUE THREAD

**Issue by Romakita** [bpetetot/conference-hall-beta#911]
Hello @bpetetot 

I have a problem with conference.io, when I click on the shared link by our organizer, I haven't the list of proposed meetup and I can't vote.

Here is the link: https://conference-hall.io/organizer/event/VP2QLhZyZRQVDtzWlLtk/proposals

My account is linked to my github account for information :)

See you
Romain

**Comment by bpetetot** [comment]
You have to be added as member of the event organisation to be able to see the event.
Ask to your organizer, if it has added you as organizer (the right email account) or ask him to send you an invite link to the organization, and then you will just have to connect with the right account.
