### ISSUE TITLE
Event not found on my organization

### ISSUE THREAD

**Issue by utix** [bpetetot/conference-hall-beta#917]
The following event
https://conference-hall.io/public/event/fmeozXWRm0GRLBO7ruFv

is not present in the organization
https://conference-hall.io/organizer/organization/CuQAZuya6yTSsByAtWnj

Any idea why ?

**Comment by bpetetot** [comment]
On the event configuration page (when you edit it) you have to link it to the organisation (there is a combo box with all your organizations) So after association, all members of your organization will have access to the event.
