### ISSUE TITLE
Survey speaker accommodation

### ISSUE THREAD

**Issue by olivMertens** [bpetetot/conference-hall-beta#918]
**Description**
When i entered information on my speaker form, theses data can't be reset  ( so maybe bug ? ) and it could be interesting to mitigate theses informations by event ?

**Comment by bpetetot** [comment]
These information are managed by event. If you go back to the event, then on the side-bar menu (on the left), you should see "Survey" and you can update it.

**Comment by olivMertens** [comment]
Not enough research i guess :)
