### ISSUE TITLE
Email Server not properly configured

### ISSUE THREAD

**Issue by HugoGresse** [bpetetot/conference-hall-beta#921]
I've run some test using mail-tester.com 
And here is the results: 
Note: 5.9 / 10 

I believe most configuration should be pretty easy following mailgun recommendation: 

# 1. Add dmarc

Vous n'avez pas d'enregistrement DMARC, veuillez ajouter une entrée TXT à votre domaine _dmarc.mg.conference-hall.io avec la valeur suivante :

v=DMARC1; p=none

# 2. Adding MX Record

Nous vérifions si vous avez un serveur email (MX Record) derrière votre nom de domaine mg.conference-hall.io

Vous devriez publier une entrée DNS (de type MX) sur votre nom de domaine mg.conference-hall.io ou utiliser une adresse de rebond différente.

More details: https://www.mail-tester.com/test-dra0odrlx 
To run the test, I've created an account with gmail and changed the email by editing the profil. 

I've included a copy of the report: 
![image](https://user-images.githubusercontent.com/662377/161762309-975b25ee-aa3f-4c92-9181-654e419cc19d.png)

**Comment by bpetetot** [comment]
Oh thanks a lot @HugoGresse 🙏  I'm going to check that.

**Comment by bpetetot** [comment]
@HugoGresse 
I have added MX and TXT DMARC records, and it seems much better ;)

![image](https://user-images.githubusercontent.com/516360/161957929-b53d438d-bd76-4284-8983-96fa7b5618a5.png)

Thanks a lot for the help. 👍 

I'm going to close other related issues and watch if it happens again.

**Comment by HugoGresse** [comment]
Nice!
