### ISSUE TITLE
Cannot update submission

### ISSUE THREAD

**Issue by sinedied** [bpetetot/conference-hall-beta#948]
Hello!

I was trying to update one of my submission, and it always fails with this error (showing just "internal error" on the tool):

![image](https://user-images.githubusercontent.com/593151/207014907-0a209ecd-9294-48a3-95ae-d651eeca6570.png)

I cannot remove my submission too (to resubmit it), same error.

**Comment by bpetetot** [comment]
Thanks @sinedied for the feedback, I'm going to check.
Which event/conference is it?

**Comment by sinedied** [comment]
It's for Sunny Tech 2023

**Comment by bpetetot** [comment]
Can you retry? It seems the server were not in a good shape last week. Thanks ;)

**Comment by sinedied** [comment]
Tried today, it worked! Thanks 🙂
