### ISSUE TITLE
login via twitter ne fonctionne pas

### ISSUE THREAD

**Issue by Angi-g** [bpetetot/conference-hall-beta#971]
**What is the issue?**
 J’ai un compte existant, j'ai déjà soumis des talks avec,
 Je suis sur la page de connexion, je tente de me connecter via le bouton twitter, mais l'authentification ne se fait pas, j'ai le message d'erreur "Firebase: The supplied auth credential is malformed or has expired. (auth/invalid-credential)."
**What is the expected behavior?**
une connexion a mon profil * - *
**What is your environment?**

- OS: windows
- Browser: chrome (j'ai aussi essayé sur firfox)

**Comment by bpetetot** [comment]
Hi @Angi-g, merci pour le retour.
Le problème doit être normalement corrigé. Peux-tu me confirmer si ça fonctionne pour toi ?

**Comment by Angi-g** [comment]
C'est good, je confirme, merci !
