### ISSUE TITLE
Same GUID for 2 conference formats

### ISSUE THREAD

**Issue by bmaxime-c** [bpetetot/conference-hall-beta#976]
**What is the issue?**
When exporting conferences via API, I have 2 formats with same GUID.

```
{
    "name": "Conférence courte (20 minutes)",
    "id": "d66dab59-d2ce-575a-84e4-249e6055fe24"
},
{
    "name": "Atelier long (90 minutes)",
    "id": "d66dab59-d2ce-575a-84e4-249e6055fe24"
},
```

**What is the expected behavior?**
Each format should have a distinct GUID. Is it possible to fix that with a new GUID and fix incorrect data?

**What is your environment?**

- OS: Windows
- Browser: Google Chrome
- EventId: mXxbggAyDUbTFXazxkWX

**Comment by bmaxime-c** [comment]
I saw that we can modify the talk data by ourselves. So we did it by creating a new format, fixing where it was bad and deleting the duplicated format.
Didn't see that there is already another issue, so I close mine.
Other issue is #872

**Comment by bpetetot** [comment]
Sorry for the delay. Glad you find a solution.
I'm going to investigate what happens.
